### ISSUE TITLE
Rename default branch to 'main'

### ISSUE THREAD

**Issue by simonwhatley** [ministryofjustice/moj-design-system#57]
Rename `master` to `main`, which is more meaningful and inclusive.

See https://github.com/github/renaming

**Comment by gregtyler** [comment]
GDS recently did this for the GOV.UK design system and provide some [migration directions](https://github.com/alphagov/govuk-design-system/issues/1597). We should add some similar instructions here after we perform the rename.

**Comment by gregtyler** [comment]
Issue was auto-closed by a PR merge, re-opening whilst I deal with the other repos.
